export const materialData = [
    { id: 1, name: "Бур 12х160мм", measure: "шт." },
    { id: 2, name: "Бур 14х160мм", measure: "шт." },
    { id: 3, name: "ГКЛ-А-Плук 2500*1200*9,5(67)", measure: "шт." },
    { id: 4, name: "ГКЛ-В-Плук 2500*1200*12,5(51)", measure: "шт." },
    { id: 5, name: "ГКЛ-В-Плук 2500*1200*9,5(67)", measure: "шт." },
    { id: 6, name: "Головка М8", measure: "шт." },
    { id: 7, name: "Грунтовка AlinEX PRIMER, 10кг", measure: "канистра" },
    { id: 8, name: "Гвозди жидкие", measure: "шт." },
    { id: 9, name: "Диск алмазный Кристал, 115мм", measure: "шт." },
    { id: 10, name: "Диск отрезной Rodex, 180мм", measure: "шт." },
    { id: 11, name: "Диск отрезной для плитки Bollein, 125мм", measure: "шт." },
    { id: 12, name: "Диск отрезной для плитки Максимум, 125мм", measure: "шт." },
    { id: 13, name: "Диск отрезной для плитки Максимум, 180мм", measure: "шт." },
    { id: 14, name: "Доставка", measure: "рейс" },
    { id: 15, name: "Жидкий гвоздь", measure: "шт." },
    { id: 16, name: "Зонт 12х180", measure: "шт." },
    { id: 17, name: "Затирка CE33 графитовый", measure: "кг" },
    { id: 18, name: "Затирка CE33 серый", measure: "кг" },
    { id: 19, name: "Затирка CE33 серый, 2кг", measure: "пачка" },
    { id: 20, name: "Кабель ВВГ, 3х2.5", measure: "м." },
    { id: 21, name: "Кабель ПВС, 3х4", measure: "м." },
    { id: 22, name: "Кабель ПВС, 4х4", measure: "м." },
    { id: 23, name: "Кабель канал, 40х25", measure: "хлыст" },
    { id: 24, name: "Кабель канал, 60х40", measure: "хлыст" },
    { id: 25, name: "Канцелярный нож", measure: "шт." },
    { id: 26, name: "Карандаш строительный, черный", measure: "шт." },
    { id: 27, name: "Клей AlinEX SET 300, 25кг", measure: "мешок" },
    { id: 28, name: "Клей AlinEX SET 302, 25кг", measure: "мешок" },
    { id: 29, name: "Клей двухкомпонентный Akfix, 500гр.", measure: "шт." },
    { id: 30, name: "Колодка тройная", measure: "шт." },
    { id: 31, name: "Коронка по кафелю, 35мм", measure: "шт." },
    { id: 32, name: "Крестик для кафеля", measure: "п." },
    { id: 33, name: "Лезвие для малярного ножа", measure: "пачка" },
    { id: 34, name: "Маркер строительный", measure: "шт." },
    { id: 35, name: "Маркер тонкий", measure: "шт." },
    { id: 36, name: "Маркер толстый", measure: "шт." },
    { id: 37, name: "Мешок", measure: "шт." },
    { id: 38, name: "Мешок мусорный", measure: "шт." },
    { id: 39, name: "Мотыга", measure: "шт." },
    { id: 40, name: "Отвертка большая", measure: "шт." },
    { id: 41, name: "Отвертка маленькая", measure: "шт." },
    { id: 42, name: "Пена Homefix", measure: "шт." },
    { id: 43, name: "Пена клей Акфикс", measure: "шт." },
    { id: 44, name: "Пенаплекс 3ка 240К", measure: "шт." },
    { id: 45, name: "Перчатки летние", measure: "шт." },
    { id: 46, name: "Перчатки салатовые", measure: "пара" },
    { id: 47, name: "Плинтус Н80", measure: "шт." },
    { id: 48, name: "Подрозетник глубокий", measure: "шт." },
    { id: 49, name: "Правила, 2м", measure: "шт." },
    { id: 50, name: "Проволка, 2м", measure: "шт." },
    { id: 51, name: "Растворитель Уайт-Спирт, 5лт.", measure: "канистра" },
    { id: 52, name: "Саморез кровельный по металлу A&T 5,5x50", measure: "кг." },
    { id: 53, name: "Cаморез кровельный, антрацит", measure: "кг." },
    { id: 54, name: "Светоотражающий жилет", measure: "шт." },
    { id: 55, name: "СВП зажим 1.5см", measure: "пачка" },
    { id: 56, name: "Сеткамак ВР4, 150х150мм", measure: "шт." },
    { id: 57, name: "Силикон прозоранчый", measure: "шт." },
    { id: 58, name: "Скотч армированный, 5х30", measure: "шт." },
    { id: 59, name: "Скотч бумажный, 5см", measure: "шт." },
    { id: 60, name: "Скотч прозрачный", measure: "шт." },
    { id: 62, name: "Сверло (Ёлочка)", measure: "шт." },
    { id: 63, name: "Труба 10см, 2м", measure: "шт." },
    { id: 64, name: "Труба 10см, 1м", measure: "шт." },
    { id: 65, name: "Отвод 10S", measure: "шт." },
    { id: 66, name: "Цемент М450", measure: "м." },
    { id: 67, name: "Шпатлевка AlinEX FINISH, 25кг(полимерная)", measure: "шт." },
    { id: 68, name: "Шпатлевка AlinEX GLATT, 25кг", measure: "шт." },
    { id: 69, name: "Валик 5 в 1 Июхой, 100мм", measure: "шт." },
    { id: 70, name: "Валик Июхой, 220мм", measure: "шт." },
    { id: 71, name: "Вилка кабельная", measure: "шт." },
    { id: 72, name: "Электрод Арсенал №3", measure: "пачка" }
  ];
  